### ISSUE TITLE
Choose new name for the project

### ISSUE THREAD

**Issue by FilipDominec** [FilipDominec/plotcommander#3]
While the working name ```plotcommander``` may suggest that the application draws some plots and that it may be somewhat similar to the file browsing applications like *norton commander* or *total commander*, I do not like this name too much. It is long and boring, and it does not convey how I enjoy swiftly viewing and processing many files with experimental data on my computer. 

What about a shortcut? Data Under Your Fingers? ```DUYF```? It is short and still no project with such a name exists on github. 

Or something a bit crazy? I considered ```GayPlot``` since the rainbow color palette, generated to distinguish multiple plotted datasets, resembles the rainbow flag of LGBT. Friends told me that some people may be sensitive to such a pun of minorities and may find it confusing and perhaps offensive, though. I can not tell.

Or forget about that some names have been already claimed by other projects and name it like ```Correlation```, ```Discovery``` or ```Insight``` (since this is roughly what I search in the data)? Or ```Eureka```?

Feel free to give me your opinion and tips!

**Comment by FilipDominec** [comment]
`datdiff` is also an unique name and it partially describes what the program is useful for...

**Comment by roesel** [comment]
How about `complot` - a nice alternative to `plot commander` ;).

**Comment by FilipDominec** [comment]
@roesel I like this idea, but there exist at least these projects: https://github.com/peterallenwebb/COMPLOT and https://github.com/Depaulicious/ComPlot. And they are also focused on graph plotting, so I guess it might be confusing to add a third plotting app.

**Comment by FilipDominec** [comment]
```pysveic``` = PYthon Scientific Visualisation Executing Inline Commands ?
